# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Mariana Arboleda"
resume_title:                   "Estudiante de Doctorado en Educación"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "marianaarboleda@uninorte.edu.co"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "3122386367"
resume_contact_address:         "Barranquilla, Colombia"

resume_header_contact_info:     "Barranquilla, Colombia • marianaarboleda@uninorte.edu.co"
display_header_contact_info:    "true"

resume_header_intro: "<p>Mi tema de investigación se centra al rededor de la educación en Ciencia de Datos. Me interesa el desarrollo de habilidades de programación, pensamiento computacional y análisis de datos, para todas y todos.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
#associations means (for me) teacher experience
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_website_url:           "https://marianaarboleda.github.io/"
  resume_github_url:            "https://github.com/marianaarboleda"
  resume_twitter_url:           "http://twitter.com/marbolf"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_medium_url:            "https://medium.com/@jglovier"
  resume_download_url:          "https://github.com/marianaarboleda/hoja_de_vida/files/12777751/mariana_arboleda_hv.pdf"
  resume_english_url:           "https://marianaarboleda.github.io/academic_cv/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
